// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_chat_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_chat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_chat_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_chat_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chat_2eproto;
namespace chat {
class AddFriendReq;
struct AddFriendReqDefaultTypeInternal;
extern AddFriendReqDefaultTypeInternal _AddFriendReq_default_instance_;
class AddGroupReq;
struct AddGroupReqDefaultTypeInternal;
extern AddGroupReqDefaultTypeInternal _AddGroupReq_default_instance_;
class CreategroupReq;
struct CreategroupReqDefaultTypeInternal;
extern CreategroupReqDefaultTypeInternal _CreategroupReq_default_instance_;
class GroupChatReq;
struct GroupChatReqDefaultTypeInternal;
extern GroupChatReqDefaultTypeInternal _GroupChatReq_default_instance_;
class LoginReq;
struct LoginReqDefaultTypeInternal;
extern LoginReqDefaultTypeInternal _LoginReq_default_instance_;
class LoginRes;
struct LoginResDefaultTypeInternal;
extern LoginResDefaultTypeInternal _LoginRes_default_instance_;
class LogoutReq;
struct LogoutReqDefaultTypeInternal;
extern LogoutReqDefaultTypeInternal _LogoutReq_default_instance_;
class OneChatReq;
struct OneChatReqDefaultTypeInternal;
extern OneChatReqDefaultTypeInternal _OneChatReq_default_instance_;
class RegisterReq;
struct RegisterReqDefaultTypeInternal;
extern RegisterReqDefaultTypeInternal _RegisterReq_default_instance_;
class RegisterRes;
struct RegisterResDefaultTypeInternal;
extern RegisterResDefaultTypeInternal _RegisterRes_default_instance_;
}  // namespace chat
PROTOBUF_NAMESPACE_OPEN
template<> ::chat::AddFriendReq* Arena::CreateMaybeMessage<::chat::AddFriendReq>(Arena*);
template<> ::chat::AddGroupReq* Arena::CreateMaybeMessage<::chat::AddGroupReq>(Arena*);
template<> ::chat::CreategroupReq* Arena::CreateMaybeMessage<::chat::CreategroupReq>(Arena*);
template<> ::chat::GroupChatReq* Arena::CreateMaybeMessage<::chat::GroupChatReq>(Arena*);
template<> ::chat::LoginReq* Arena::CreateMaybeMessage<::chat::LoginReq>(Arena*);
template<> ::chat::LoginRes* Arena::CreateMaybeMessage<::chat::LoginRes>(Arena*);
template<> ::chat::LogoutReq* Arena::CreateMaybeMessage<::chat::LogoutReq>(Arena*);
template<> ::chat::OneChatReq* Arena::CreateMaybeMessage<::chat::OneChatReq>(Arena*);
template<> ::chat::RegisterReq* Arena::CreateMaybeMessage<::chat::RegisterReq>(Arena*);
template<> ::chat::RegisterRes* Arena::CreateMaybeMessage<::chat::RegisterRes>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chat {

enum MsgTyp : int {
  Login_msg = 0,
  Login_msg_ack = 1,
  Reg_mag = 2,
  Reg_msg_ack = 3,
  Add_msg = 4,
  Onechat_msg = 5,
  Creategroup_msg = 6,
  Addgroup_msg = 7,
  Groupchat_msg = 8,
  Logout_msg = 9,
  MsgTyp_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MsgTyp_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MsgTyp_IsValid(int value);
constexpr MsgTyp MsgTyp_MIN = Login_msg;
constexpr MsgTyp MsgTyp_MAX = Logout_msg;
constexpr int MsgTyp_ARRAYSIZE = MsgTyp_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MsgTyp_descriptor();
template<typename T>
inline const std::string& MsgTyp_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MsgTyp>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MsgTyp_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MsgTyp_descriptor(), enum_t_value);
}
inline bool MsgTyp_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MsgTyp* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MsgTyp>(
    MsgTyp_descriptor(), name, value);
}
// ===================================================================

class LoginReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.LoginReq) */ {
 public:
  inline LoginReq() : LoginReq(nullptr) {}
  ~LoginReq() override;
  explicit PROTOBUF_CONSTEXPR LoginReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginReq(const LoginReq& from);
  LoginReq(LoginReq&& from) noexcept
    : LoginReq() {
    *this = ::std::move(from);
  }

  inline LoginReq& operator=(const LoginReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginReq& operator=(LoginReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginReq* internal_default_instance() {
    return reinterpret_cast<const LoginReq*>(
               &_LoginReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LoginReq& a, LoginReq& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginReq& from) {
    LoginReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.LoginReq";
  }
  protected:
  explicit LoginReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPasswordFieldNumber = 3,
    kMsgidFieldNumber = 1,
    kUseridFieldNumber = 2,
  };
  // string password = 3;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 userid = 2;
  void clear_userid();
  int32_t userid() const;
  void set_userid(int32_t value);
  private:
  int32_t _internal_userid() const;
  void _internal_set_userid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.LoginReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    int32_t msgid_;
    int32_t userid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class LoginRes final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.LoginRes) */ {
 public:
  inline LoginRes() : LoginRes(nullptr) {}
  ~LoginRes() override;
  explicit PROTOBUF_CONSTEXPR LoginRes(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LoginRes(const LoginRes& from);
  LoginRes(LoginRes&& from) noexcept
    : LoginRes() {
    *this = ::std::move(from);
  }

  inline LoginRes& operator=(const LoginRes& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginRes& operator=(LoginRes&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginRes& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginRes* internal_default_instance() {
    return reinterpret_cast<const LoginRes*>(
               &_LoginRes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LoginRes& a, LoginRes& b) {
    a.Swap(&b);
  }
  inline void Swap(LoginRes* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginRes* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginRes* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LoginRes>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LoginRes& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LoginRes& from) {
    LoginRes::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoginRes* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.LoginRes";
  }
  protected:
  explicit LoginRes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrmsgFieldNumber = 3,
    kMsgidFieldNumber = 1,
    kErrFieldNumber = 2,
  };
  // string errmsg = 3;
  void clear_errmsg();
  const std::string& errmsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errmsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errmsg();
  PROTOBUF_NODISCARD std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 err = 2;
  void clear_err();
  int32_t err() const;
  void set_err(int32_t value);
  private:
  int32_t _internal_err() const;
  void _internal_set_err(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.LoginRes)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
    int32_t msgid_;
    int32_t err_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class RegisterReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.RegisterReq) */ {
 public:
  inline RegisterReq() : RegisterReq(nullptr) {}
  ~RegisterReq() override;
  explicit PROTOBUF_CONSTEXPR RegisterReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RegisterReq(const RegisterReq& from);
  RegisterReq(RegisterReq&& from) noexcept
    : RegisterReq() {
    *this = ::std::move(from);
  }

  inline RegisterReq& operator=(const RegisterReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterReq& operator=(RegisterReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RegisterReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const RegisterReq* internal_default_instance() {
    return reinterpret_cast<const RegisterReq*>(
               &_RegisterReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RegisterReq& a, RegisterReq& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RegisterReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RegisterReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RegisterReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RegisterReq& from) {
    RegisterReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.RegisterReq";
  }
  protected:
  explicit RegisterReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kPasswordFieldNumber = 3,
    kMsgidFieldNumber = 1,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string password = 3;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.RegisterReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    int32_t msgid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class RegisterRes final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.RegisterRes) */ {
 public:
  inline RegisterRes() : RegisterRes(nullptr) {}
  ~RegisterRes() override;
  explicit PROTOBUF_CONSTEXPR RegisterRes(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RegisterRes(const RegisterRes& from);
  RegisterRes(RegisterRes&& from) noexcept
    : RegisterRes() {
    *this = ::std::move(from);
  }

  inline RegisterRes& operator=(const RegisterRes& from) {
    CopyFrom(from);
    return *this;
  }
  inline RegisterRes& operator=(RegisterRes&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RegisterRes& default_instance() {
    return *internal_default_instance();
  }
  static inline const RegisterRes* internal_default_instance() {
    return reinterpret_cast<const RegisterRes*>(
               &_RegisterRes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RegisterRes& a, RegisterRes& b) {
    a.Swap(&b);
  }
  inline void Swap(RegisterRes* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RegisterRes* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RegisterRes* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RegisterRes>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RegisterRes& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RegisterRes& from) {
    RegisterRes::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RegisterRes* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.RegisterRes";
  }
  protected:
  explicit RegisterRes(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgidFieldNumber = 1,
    kErrFieldNumber = 2,
    kUseridFieldNumber = 3,
  };
  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 err = 2;
  void clear_err();
  int32_t err() const;
  void set_err(int32_t value);
  private:
  int32_t _internal_err() const;
  void _internal_set_err(int32_t value);
  public:

  // int32 userid = 3;
  void clear_userid();
  int32_t userid() const;
  void set_userid(int32_t value);
  private:
  int32_t _internal_userid() const;
  void _internal_set_userid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.RegisterRes)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t msgid_;
    int32_t err_;
    int32_t userid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class AddFriendReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.AddFriendReq) */ {
 public:
  inline AddFriendReq() : AddFriendReq(nullptr) {}
  ~AddFriendReq() override;
  explicit PROTOBUF_CONSTEXPR AddFriendReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddFriendReq(const AddFriendReq& from);
  AddFriendReq(AddFriendReq&& from) noexcept
    : AddFriendReq() {
    *this = ::std::move(from);
  }

  inline AddFriendReq& operator=(const AddFriendReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddFriendReq& operator=(AddFriendReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddFriendReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddFriendReq* internal_default_instance() {
    return reinterpret_cast<const AddFriendReq*>(
               &_AddFriendReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AddFriendReq& a, AddFriendReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AddFriendReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddFriendReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddFriendReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddFriendReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddFriendReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddFriendReq& from) {
    AddFriendReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddFriendReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.AddFriendReq";
  }
  protected:
  explicit AddFriendReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgidFieldNumber = 1,
    kUseridFieldNumber = 2,
    kFriendidFieldNumber = 3,
  };
  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 userid = 2;
  void clear_userid();
  int32_t userid() const;
  void set_userid(int32_t value);
  private:
  int32_t _internal_userid() const;
  void _internal_set_userid(int32_t value);
  public:

  // int32 friendid = 3;
  void clear_friendid();
  int32_t friendid() const;
  void set_friendid(int32_t value);
  private:
  int32_t _internal_friendid() const;
  void _internal_set_friendid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.AddFriendReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t msgid_;
    int32_t userid_;
    int32_t friendid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class OneChatReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.OneChatReq) */ {
 public:
  inline OneChatReq() : OneChatReq(nullptr) {}
  ~OneChatReq() override;
  explicit PROTOBUF_CONSTEXPR OneChatReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OneChatReq(const OneChatReq& from);
  OneChatReq(OneChatReq&& from) noexcept
    : OneChatReq() {
    *this = ::std::move(from);
  }

  inline OneChatReq& operator=(const OneChatReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneChatReq& operator=(OneChatReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OneChatReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const OneChatReq* internal_default_instance() {
    return reinterpret_cast<const OneChatReq*>(
               &_OneChatReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(OneChatReq& a, OneChatReq& b) {
    a.Swap(&b);
  }
  inline void Swap(OneChatReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneChatReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OneChatReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OneChatReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OneChatReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OneChatReq& from) {
    OneChatReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OneChatReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.OneChatReq";
  }
  protected:
  explicit OneChatReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 4,
    kMsgidFieldNumber = 1,
    kFromidFieldNumber = 2,
    kToidFieldNumber = 3,
  };
  // string msg = 4;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 fromid = 2;
  void clear_fromid();
  int32_t fromid() const;
  void set_fromid(int32_t value);
  private:
  int32_t _internal_fromid() const;
  void _internal_set_fromid(int32_t value);
  public:

  // int32 toid = 3;
  void clear_toid();
  int32_t toid() const;
  void set_toid(int32_t value);
  private:
  int32_t _internal_toid() const;
  void _internal_set_toid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.OneChatReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    int32_t msgid_;
    int32_t fromid_;
    int32_t toid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class CreategroupReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.CreategroupReq) */ {
 public:
  inline CreategroupReq() : CreategroupReq(nullptr) {}
  ~CreategroupReq() override;
  explicit PROTOBUF_CONSTEXPR CreategroupReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CreategroupReq(const CreategroupReq& from);
  CreategroupReq(CreategroupReq&& from) noexcept
    : CreategroupReq() {
    *this = ::std::move(from);
  }

  inline CreategroupReq& operator=(const CreategroupReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreategroupReq& operator=(CreategroupReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreategroupReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const CreategroupReq* internal_default_instance() {
    return reinterpret_cast<const CreategroupReq*>(
               &_CreategroupReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(CreategroupReq& a, CreategroupReq& b) {
    a.Swap(&b);
  }
  inline void Swap(CreategroupReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreategroupReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreategroupReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CreategroupReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CreategroupReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CreategroupReq& from) {
    CreategroupReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreategroupReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.CreategroupReq";
  }
  protected:
  explicit CreategroupReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGroupnameFieldNumber = 3,
    kGroupdescFieldNumber = 4,
    kMsgidFieldNumber = 1,
    kUseridFieldNumber = 2,
  };
  // string groupname = 3;
  void clear_groupname();
  const std::string& groupname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_groupname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_groupname();
  PROTOBUF_NODISCARD std::string* release_groupname();
  void set_allocated_groupname(std::string* groupname);
  private:
  const std::string& _internal_groupname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_groupname(const std::string& value);
  std::string* _internal_mutable_groupname();
  public:

  // string groupdesc = 4;
  void clear_groupdesc();
  const std::string& groupdesc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_groupdesc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_groupdesc();
  PROTOBUF_NODISCARD std::string* release_groupdesc();
  void set_allocated_groupdesc(std::string* groupdesc);
  private:
  const std::string& _internal_groupdesc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_groupdesc(const std::string& value);
  std::string* _internal_mutable_groupdesc();
  public:

  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 userid = 2;
  void clear_userid();
  int32_t userid() const;
  void set_userid(int32_t value);
  private:
  int32_t _internal_userid() const;
  void _internal_set_userid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.CreategroupReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr groupname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr groupdesc_;
    int32_t msgid_;
    int32_t userid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class AddGroupReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.AddGroupReq) */ {
 public:
  inline AddGroupReq() : AddGroupReq(nullptr) {}
  ~AddGroupReq() override;
  explicit PROTOBUF_CONSTEXPR AddGroupReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AddGroupReq(const AddGroupReq& from);
  AddGroupReq(AddGroupReq&& from) noexcept
    : AddGroupReq() {
    *this = ::std::move(from);
  }

  inline AddGroupReq& operator=(const AddGroupReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddGroupReq& operator=(AddGroupReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddGroupReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddGroupReq* internal_default_instance() {
    return reinterpret_cast<const AddGroupReq*>(
               &_AddGroupReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(AddGroupReq& a, AddGroupReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AddGroupReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddGroupReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddGroupReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AddGroupReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AddGroupReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AddGroupReq& from) {
    AddGroupReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddGroupReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.AddGroupReq";
  }
  protected:
  explicit AddGroupReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgidFieldNumber = 1,
    kUseridFieldNumber = 2,
    kGroupidFieldNumber = 3,
  };
  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 userid = 2;
  void clear_userid();
  int32_t userid() const;
  void set_userid(int32_t value);
  private:
  int32_t _internal_userid() const;
  void _internal_set_userid(int32_t value);
  public:

  // int32 groupid = 3;
  void clear_groupid();
  int32_t groupid() const;
  void set_groupid(int32_t value);
  private:
  int32_t _internal_groupid() const;
  void _internal_set_groupid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.AddGroupReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t msgid_;
    int32_t userid_;
    int32_t groupid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class GroupChatReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.GroupChatReq) */ {
 public:
  inline GroupChatReq() : GroupChatReq(nullptr) {}
  ~GroupChatReq() override;
  explicit PROTOBUF_CONSTEXPR GroupChatReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GroupChatReq(const GroupChatReq& from);
  GroupChatReq(GroupChatReq&& from) noexcept
    : GroupChatReq() {
    *this = ::std::move(from);
  }

  inline GroupChatReq& operator=(const GroupChatReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline GroupChatReq& operator=(GroupChatReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GroupChatReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const GroupChatReq* internal_default_instance() {
    return reinterpret_cast<const GroupChatReq*>(
               &_GroupChatReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(GroupChatReq& a, GroupChatReq& b) {
    a.Swap(&b);
  }
  inline void Swap(GroupChatReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GroupChatReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GroupChatReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GroupChatReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GroupChatReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GroupChatReq& from) {
    GroupChatReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GroupChatReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.GroupChatReq";
  }
  protected:
  explicit GroupChatReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 4,
    kMsgidFieldNumber = 1,
    kUseridFieldNumber = 2,
    kGroupidFieldNumber = 3,
  };
  // string msg = 4;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 userid = 2;
  void clear_userid();
  int32_t userid() const;
  void set_userid(int32_t value);
  private:
  int32_t _internal_userid() const;
  void _internal_set_userid(int32_t value);
  public:

  // int32 groupid = 3;
  void clear_groupid();
  int32_t groupid() const;
  void set_groupid(int32_t value);
  private:
  int32_t _internal_groupid() const;
  void _internal_set_groupid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.GroupChatReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    int32_t msgid_;
    int32_t userid_;
    int32_t groupid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// -------------------------------------------------------------------

class LogoutReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chat.LogoutReq) */ {
 public:
  inline LogoutReq() : LogoutReq(nullptr) {}
  ~LogoutReq() override;
  explicit PROTOBUF_CONSTEXPR LogoutReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LogoutReq(const LogoutReq& from);
  LogoutReq(LogoutReq&& from) noexcept
    : LogoutReq() {
    *this = ::std::move(from);
  }

  inline LogoutReq& operator=(const LogoutReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogoutReq& operator=(LogoutReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LogoutReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const LogoutReq* internal_default_instance() {
    return reinterpret_cast<const LogoutReq*>(
               &_LogoutReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  friend void swap(LogoutReq& a, LogoutReq& b) {
    a.Swap(&b);
  }
  inline void Swap(LogoutReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogoutReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LogoutReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LogoutReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LogoutReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LogoutReq& from) {
    LogoutReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogoutReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chat.LogoutReq";
  }
  protected:
  explicit LogoutReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgidFieldNumber = 1,
    kUseridFieldNumber = 2,
  };
  // int32 msgid = 1;
  void clear_msgid();
  int32_t msgid() const;
  void set_msgid(int32_t value);
  private:
  int32_t _internal_msgid() const;
  void _internal_set_msgid(int32_t value);
  public:

  // int32 userid = 2;
  void clear_userid();
  int32_t userid() const;
  void set_userid(int32_t value);
  private:
  int32_t _internal_userid() const;
  void _internal_set_userid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:chat.LogoutReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t msgid_;
    int32_t userid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LoginReq

// int32 msgid = 1;
inline void LoginReq::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t LoginReq::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t LoginReq::msgid() const {
  // @@protoc_insertion_point(field_get:chat.LoginReq.msgid)
  return _internal_msgid();
}
inline void LoginReq::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void LoginReq::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.LoginReq.msgid)
}

// int32 userid = 2;
inline void LoginReq::clear_userid() {
  _impl_.userid_ = 0;
}
inline int32_t LoginReq::_internal_userid() const {
  return _impl_.userid_;
}
inline int32_t LoginReq::userid() const {
  // @@protoc_insertion_point(field_get:chat.LoginReq.userid)
  return _internal_userid();
}
inline void LoginReq::_internal_set_userid(int32_t value) {
  
  _impl_.userid_ = value;
}
inline void LoginReq::set_userid(int32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:chat.LoginReq.userid)
}

// string password = 3;
inline void LoginReq::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& LoginReq::password() const {
  // @@protoc_insertion_point(field_get:chat.LoginReq.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginReq::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.LoginReq.password)
}
inline std::string* LoginReq::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:chat.LoginReq.password)
  return _s;
}
inline const std::string& LoginReq::_internal_password() const {
  return _impl_.password_.Get();
}
inline void LoginReq::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginReq::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginReq::release_password() {
  // @@protoc_insertion_point(field_release:chat.LoginReq.password)
  return _impl_.password_.Release();
}
inline void LoginReq::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.LoginReq.password)
}

// -------------------------------------------------------------------

// LoginRes

// int32 msgid = 1;
inline void LoginRes::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t LoginRes::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t LoginRes::msgid() const {
  // @@protoc_insertion_point(field_get:chat.LoginRes.msgid)
  return _internal_msgid();
}
inline void LoginRes::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void LoginRes::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.LoginRes.msgid)
}

// int32 err = 2;
inline void LoginRes::clear_err() {
  _impl_.err_ = 0;
}
inline int32_t LoginRes::_internal_err() const {
  return _impl_.err_;
}
inline int32_t LoginRes::err() const {
  // @@protoc_insertion_point(field_get:chat.LoginRes.err)
  return _internal_err();
}
inline void LoginRes::_internal_set_err(int32_t value) {
  
  _impl_.err_ = value;
}
inline void LoginRes::set_err(int32_t value) {
  _internal_set_err(value);
  // @@protoc_insertion_point(field_set:chat.LoginRes.err)
}

// string errmsg = 3;
inline void LoginRes::clear_errmsg() {
  _impl_.errmsg_.ClearToEmpty();
}
inline const std::string& LoginRes::errmsg() const {
  // @@protoc_insertion_point(field_get:chat.LoginRes.errmsg)
  return _internal_errmsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LoginRes::set_errmsg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errmsg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.LoginRes.errmsg)
}
inline std::string* LoginRes::mutable_errmsg() {
  std::string* _s = _internal_mutable_errmsg();
  // @@protoc_insertion_point(field_mutable:chat.LoginRes.errmsg)
  return _s;
}
inline const std::string& LoginRes::_internal_errmsg() const {
  return _impl_.errmsg_.Get();
}
inline void LoginRes::_internal_set_errmsg(const std::string& value) {
  
  _impl_.errmsg_.Set(value, GetArenaForAllocation());
}
inline std::string* LoginRes::_internal_mutable_errmsg() {
  
  return _impl_.errmsg_.Mutable(GetArenaForAllocation());
}
inline std::string* LoginRes::release_errmsg() {
  // @@protoc_insertion_point(field_release:chat.LoginRes.errmsg)
  return _impl_.errmsg_.Release();
}
inline void LoginRes::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  _impl_.errmsg_.SetAllocated(errmsg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errmsg_.IsDefault()) {
    _impl_.errmsg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.LoginRes.errmsg)
}

// -------------------------------------------------------------------

// RegisterReq

// int32 msgid = 1;
inline void RegisterReq::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t RegisterReq::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t RegisterReq::msgid() const {
  // @@protoc_insertion_point(field_get:chat.RegisterReq.msgid)
  return _internal_msgid();
}
inline void RegisterReq::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void RegisterReq::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.RegisterReq.msgid)
}

// string name = 2;
inline void RegisterReq::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& RegisterReq::name() const {
  // @@protoc_insertion_point(field_get:chat.RegisterReq.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RegisterReq::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.RegisterReq.name)
}
inline std::string* RegisterReq::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:chat.RegisterReq.name)
  return _s;
}
inline const std::string& RegisterReq::_internal_name() const {
  return _impl_.name_.Get();
}
inline void RegisterReq::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* RegisterReq::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* RegisterReq::release_name() {
  // @@protoc_insertion_point(field_release:chat.RegisterReq.name)
  return _impl_.name_.Release();
}
inline void RegisterReq::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.RegisterReq.name)
}

// string password = 3;
inline void RegisterReq::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& RegisterReq::password() const {
  // @@protoc_insertion_point(field_get:chat.RegisterReq.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RegisterReq::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.RegisterReq.password)
}
inline std::string* RegisterReq::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:chat.RegisterReq.password)
  return _s;
}
inline const std::string& RegisterReq::_internal_password() const {
  return _impl_.password_.Get();
}
inline void RegisterReq::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* RegisterReq::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* RegisterReq::release_password() {
  // @@protoc_insertion_point(field_release:chat.RegisterReq.password)
  return _impl_.password_.Release();
}
inline void RegisterReq::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.RegisterReq.password)
}

// -------------------------------------------------------------------

// RegisterRes

// int32 msgid = 1;
inline void RegisterRes::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t RegisterRes::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t RegisterRes::msgid() const {
  // @@protoc_insertion_point(field_get:chat.RegisterRes.msgid)
  return _internal_msgid();
}
inline void RegisterRes::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void RegisterRes::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.RegisterRes.msgid)
}

// int32 err = 2;
inline void RegisterRes::clear_err() {
  _impl_.err_ = 0;
}
inline int32_t RegisterRes::_internal_err() const {
  return _impl_.err_;
}
inline int32_t RegisterRes::err() const {
  // @@protoc_insertion_point(field_get:chat.RegisterRes.err)
  return _internal_err();
}
inline void RegisterRes::_internal_set_err(int32_t value) {
  
  _impl_.err_ = value;
}
inline void RegisterRes::set_err(int32_t value) {
  _internal_set_err(value);
  // @@protoc_insertion_point(field_set:chat.RegisterRes.err)
}

// int32 userid = 3;
inline void RegisterRes::clear_userid() {
  _impl_.userid_ = 0;
}
inline int32_t RegisterRes::_internal_userid() const {
  return _impl_.userid_;
}
inline int32_t RegisterRes::userid() const {
  // @@protoc_insertion_point(field_get:chat.RegisterRes.userid)
  return _internal_userid();
}
inline void RegisterRes::_internal_set_userid(int32_t value) {
  
  _impl_.userid_ = value;
}
inline void RegisterRes::set_userid(int32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:chat.RegisterRes.userid)
}

// -------------------------------------------------------------------

// AddFriendReq

// int32 msgid = 1;
inline void AddFriendReq::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t AddFriendReq::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t AddFriendReq::msgid() const {
  // @@protoc_insertion_point(field_get:chat.AddFriendReq.msgid)
  return _internal_msgid();
}
inline void AddFriendReq::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void AddFriendReq::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.AddFriendReq.msgid)
}

// int32 userid = 2;
inline void AddFriendReq::clear_userid() {
  _impl_.userid_ = 0;
}
inline int32_t AddFriendReq::_internal_userid() const {
  return _impl_.userid_;
}
inline int32_t AddFriendReq::userid() const {
  // @@protoc_insertion_point(field_get:chat.AddFriendReq.userid)
  return _internal_userid();
}
inline void AddFriendReq::_internal_set_userid(int32_t value) {
  
  _impl_.userid_ = value;
}
inline void AddFriendReq::set_userid(int32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:chat.AddFriendReq.userid)
}

// int32 friendid = 3;
inline void AddFriendReq::clear_friendid() {
  _impl_.friendid_ = 0;
}
inline int32_t AddFriendReq::_internal_friendid() const {
  return _impl_.friendid_;
}
inline int32_t AddFriendReq::friendid() const {
  // @@protoc_insertion_point(field_get:chat.AddFriendReq.friendid)
  return _internal_friendid();
}
inline void AddFriendReq::_internal_set_friendid(int32_t value) {
  
  _impl_.friendid_ = value;
}
inline void AddFriendReq::set_friendid(int32_t value) {
  _internal_set_friendid(value);
  // @@protoc_insertion_point(field_set:chat.AddFriendReq.friendid)
}

// -------------------------------------------------------------------

// OneChatReq

// int32 msgid = 1;
inline void OneChatReq::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t OneChatReq::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t OneChatReq::msgid() const {
  // @@protoc_insertion_point(field_get:chat.OneChatReq.msgid)
  return _internal_msgid();
}
inline void OneChatReq::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void OneChatReq::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.OneChatReq.msgid)
}

// int32 fromid = 2;
inline void OneChatReq::clear_fromid() {
  _impl_.fromid_ = 0;
}
inline int32_t OneChatReq::_internal_fromid() const {
  return _impl_.fromid_;
}
inline int32_t OneChatReq::fromid() const {
  // @@protoc_insertion_point(field_get:chat.OneChatReq.fromid)
  return _internal_fromid();
}
inline void OneChatReq::_internal_set_fromid(int32_t value) {
  
  _impl_.fromid_ = value;
}
inline void OneChatReq::set_fromid(int32_t value) {
  _internal_set_fromid(value);
  // @@protoc_insertion_point(field_set:chat.OneChatReq.fromid)
}

// int32 toid = 3;
inline void OneChatReq::clear_toid() {
  _impl_.toid_ = 0;
}
inline int32_t OneChatReq::_internal_toid() const {
  return _impl_.toid_;
}
inline int32_t OneChatReq::toid() const {
  // @@protoc_insertion_point(field_get:chat.OneChatReq.toid)
  return _internal_toid();
}
inline void OneChatReq::_internal_set_toid(int32_t value) {
  
  _impl_.toid_ = value;
}
inline void OneChatReq::set_toid(int32_t value) {
  _internal_set_toid(value);
  // @@protoc_insertion_point(field_set:chat.OneChatReq.toid)
}

// string msg = 4;
inline void OneChatReq::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& OneChatReq::msg() const {
  // @@protoc_insertion_point(field_get:chat.OneChatReq.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OneChatReq::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.OneChatReq.msg)
}
inline std::string* OneChatReq::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:chat.OneChatReq.msg)
  return _s;
}
inline const std::string& OneChatReq::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void OneChatReq::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* OneChatReq::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* OneChatReq::release_msg() {
  // @@protoc_insertion_point(field_release:chat.OneChatReq.msg)
  return _impl_.msg_.Release();
}
inline void OneChatReq::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.OneChatReq.msg)
}

// -------------------------------------------------------------------

// CreategroupReq

// int32 msgid = 1;
inline void CreategroupReq::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t CreategroupReq::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t CreategroupReq::msgid() const {
  // @@protoc_insertion_point(field_get:chat.CreategroupReq.msgid)
  return _internal_msgid();
}
inline void CreategroupReq::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void CreategroupReq::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.CreategroupReq.msgid)
}

// int32 userid = 2;
inline void CreategroupReq::clear_userid() {
  _impl_.userid_ = 0;
}
inline int32_t CreategroupReq::_internal_userid() const {
  return _impl_.userid_;
}
inline int32_t CreategroupReq::userid() const {
  // @@protoc_insertion_point(field_get:chat.CreategroupReq.userid)
  return _internal_userid();
}
inline void CreategroupReq::_internal_set_userid(int32_t value) {
  
  _impl_.userid_ = value;
}
inline void CreategroupReq::set_userid(int32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:chat.CreategroupReq.userid)
}

// string groupname = 3;
inline void CreategroupReq::clear_groupname() {
  _impl_.groupname_.ClearToEmpty();
}
inline const std::string& CreategroupReq::groupname() const {
  // @@protoc_insertion_point(field_get:chat.CreategroupReq.groupname)
  return _internal_groupname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CreategroupReq::set_groupname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.groupname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.CreategroupReq.groupname)
}
inline std::string* CreategroupReq::mutable_groupname() {
  std::string* _s = _internal_mutable_groupname();
  // @@protoc_insertion_point(field_mutable:chat.CreategroupReq.groupname)
  return _s;
}
inline const std::string& CreategroupReq::_internal_groupname() const {
  return _impl_.groupname_.Get();
}
inline void CreategroupReq::_internal_set_groupname(const std::string& value) {
  
  _impl_.groupname_.Set(value, GetArenaForAllocation());
}
inline std::string* CreategroupReq::_internal_mutable_groupname() {
  
  return _impl_.groupname_.Mutable(GetArenaForAllocation());
}
inline std::string* CreategroupReq::release_groupname() {
  // @@protoc_insertion_point(field_release:chat.CreategroupReq.groupname)
  return _impl_.groupname_.Release();
}
inline void CreategroupReq::set_allocated_groupname(std::string* groupname) {
  if (groupname != nullptr) {
    
  } else {
    
  }
  _impl_.groupname_.SetAllocated(groupname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.groupname_.IsDefault()) {
    _impl_.groupname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.CreategroupReq.groupname)
}

// string groupdesc = 4;
inline void CreategroupReq::clear_groupdesc() {
  _impl_.groupdesc_.ClearToEmpty();
}
inline const std::string& CreategroupReq::groupdesc() const {
  // @@protoc_insertion_point(field_get:chat.CreategroupReq.groupdesc)
  return _internal_groupdesc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CreategroupReq::set_groupdesc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.groupdesc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.CreategroupReq.groupdesc)
}
inline std::string* CreategroupReq::mutable_groupdesc() {
  std::string* _s = _internal_mutable_groupdesc();
  // @@protoc_insertion_point(field_mutable:chat.CreategroupReq.groupdesc)
  return _s;
}
inline const std::string& CreategroupReq::_internal_groupdesc() const {
  return _impl_.groupdesc_.Get();
}
inline void CreategroupReq::_internal_set_groupdesc(const std::string& value) {
  
  _impl_.groupdesc_.Set(value, GetArenaForAllocation());
}
inline std::string* CreategroupReq::_internal_mutable_groupdesc() {
  
  return _impl_.groupdesc_.Mutable(GetArenaForAllocation());
}
inline std::string* CreategroupReq::release_groupdesc() {
  // @@protoc_insertion_point(field_release:chat.CreategroupReq.groupdesc)
  return _impl_.groupdesc_.Release();
}
inline void CreategroupReq::set_allocated_groupdesc(std::string* groupdesc) {
  if (groupdesc != nullptr) {
    
  } else {
    
  }
  _impl_.groupdesc_.SetAllocated(groupdesc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.groupdesc_.IsDefault()) {
    _impl_.groupdesc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.CreategroupReq.groupdesc)
}

// -------------------------------------------------------------------

// AddGroupReq

// int32 msgid = 1;
inline void AddGroupReq::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t AddGroupReq::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t AddGroupReq::msgid() const {
  // @@protoc_insertion_point(field_get:chat.AddGroupReq.msgid)
  return _internal_msgid();
}
inline void AddGroupReq::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void AddGroupReq::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.AddGroupReq.msgid)
}

// int32 userid = 2;
inline void AddGroupReq::clear_userid() {
  _impl_.userid_ = 0;
}
inline int32_t AddGroupReq::_internal_userid() const {
  return _impl_.userid_;
}
inline int32_t AddGroupReq::userid() const {
  // @@protoc_insertion_point(field_get:chat.AddGroupReq.userid)
  return _internal_userid();
}
inline void AddGroupReq::_internal_set_userid(int32_t value) {
  
  _impl_.userid_ = value;
}
inline void AddGroupReq::set_userid(int32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:chat.AddGroupReq.userid)
}

// int32 groupid = 3;
inline void AddGroupReq::clear_groupid() {
  _impl_.groupid_ = 0;
}
inline int32_t AddGroupReq::_internal_groupid() const {
  return _impl_.groupid_;
}
inline int32_t AddGroupReq::groupid() const {
  // @@protoc_insertion_point(field_get:chat.AddGroupReq.groupid)
  return _internal_groupid();
}
inline void AddGroupReq::_internal_set_groupid(int32_t value) {
  
  _impl_.groupid_ = value;
}
inline void AddGroupReq::set_groupid(int32_t value) {
  _internal_set_groupid(value);
  // @@protoc_insertion_point(field_set:chat.AddGroupReq.groupid)
}

// -------------------------------------------------------------------

// GroupChatReq

// int32 msgid = 1;
inline void GroupChatReq::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t GroupChatReq::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t GroupChatReq::msgid() const {
  // @@protoc_insertion_point(field_get:chat.GroupChatReq.msgid)
  return _internal_msgid();
}
inline void GroupChatReq::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void GroupChatReq::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.GroupChatReq.msgid)
}

// int32 userid = 2;
inline void GroupChatReq::clear_userid() {
  _impl_.userid_ = 0;
}
inline int32_t GroupChatReq::_internal_userid() const {
  return _impl_.userid_;
}
inline int32_t GroupChatReq::userid() const {
  // @@protoc_insertion_point(field_get:chat.GroupChatReq.userid)
  return _internal_userid();
}
inline void GroupChatReq::_internal_set_userid(int32_t value) {
  
  _impl_.userid_ = value;
}
inline void GroupChatReq::set_userid(int32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:chat.GroupChatReq.userid)
}

// int32 groupid = 3;
inline void GroupChatReq::clear_groupid() {
  _impl_.groupid_ = 0;
}
inline int32_t GroupChatReq::_internal_groupid() const {
  return _impl_.groupid_;
}
inline int32_t GroupChatReq::groupid() const {
  // @@protoc_insertion_point(field_get:chat.GroupChatReq.groupid)
  return _internal_groupid();
}
inline void GroupChatReq::_internal_set_groupid(int32_t value) {
  
  _impl_.groupid_ = value;
}
inline void GroupChatReq::set_groupid(int32_t value) {
  _internal_set_groupid(value);
  // @@protoc_insertion_point(field_set:chat.GroupChatReq.groupid)
}

// string msg = 4;
inline void GroupChatReq::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& GroupChatReq::msg() const {
  // @@protoc_insertion_point(field_get:chat.GroupChatReq.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GroupChatReq::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chat.GroupChatReq.msg)
}
inline std::string* GroupChatReq::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:chat.GroupChatReq.msg)
  return _s;
}
inline const std::string& GroupChatReq::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void GroupChatReq::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* GroupChatReq::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* GroupChatReq::release_msg() {
  // @@protoc_insertion_point(field_release:chat.GroupChatReq.msg)
  return _impl_.msg_.Release();
}
inline void GroupChatReq::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chat.GroupChatReq.msg)
}

// -------------------------------------------------------------------

// LogoutReq

// int32 msgid = 1;
inline void LogoutReq::clear_msgid() {
  _impl_.msgid_ = 0;
}
inline int32_t LogoutReq::_internal_msgid() const {
  return _impl_.msgid_;
}
inline int32_t LogoutReq::msgid() const {
  // @@protoc_insertion_point(field_get:chat.LogoutReq.msgid)
  return _internal_msgid();
}
inline void LogoutReq::_internal_set_msgid(int32_t value) {
  
  _impl_.msgid_ = value;
}
inline void LogoutReq::set_msgid(int32_t value) {
  _internal_set_msgid(value);
  // @@protoc_insertion_point(field_set:chat.LogoutReq.msgid)
}

// int32 userid = 2;
inline void LogoutReq::clear_userid() {
  _impl_.userid_ = 0;
}
inline int32_t LogoutReq::_internal_userid() const {
  return _impl_.userid_;
}
inline int32_t LogoutReq::userid() const {
  // @@protoc_insertion_point(field_get:chat.LogoutReq.userid)
  return _internal_userid();
}
inline void LogoutReq::_internal_set_userid(int32_t value) {
  
  _impl_.userid_ = value;
}
inline void LogoutReq::set_userid(int32_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:chat.LogoutReq.userid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace chat

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::chat::MsgTyp> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chat::MsgTyp>() {
  return ::chat::MsgTyp_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_chat_2eproto
