syntax = "proto3";
package chat;

enum MsgTyp {
    UNKNOWN_MSG = 0;

    LOGIN_MSG = 1;
    LOGIN_MSG_ACK = 2;

    REG_MSG = 3;
    REG_MSG_ACK = 4;

    ADD_FRIEND_MSG = 5;
    ADD_FRIEND_MSG_ACK = 6;

    ONE_CHAT_MSG = 7;
    ONE_CHAT_MSG_ACK = 8;

    CREATE_GROUP_MSG = 9;
    CREATE_GROUP_MSG_ACK = 10;

    ADD_GROUP_MSG = 11;
    ADD_GROUP_MSG_ACK = 12;

    GROUP_CHAT_MSG = 13;
    GROUP_CHAT_MSG_ACK = 14;

    LOGOUT_MSG = 15;
    LOGOUT_MSG_ACK = 16;

    HISTORY_MSG = 17;
    HISTORY_MSG_ACK = 18;

    FRIEND_NOTIFY_MSG = 19;
    FRIEND_NOTIFY_MSG_ACK = 20;

    QUERY_FRIEND_REQ_MSG = 21;
    QUERY_FRIEND_REQ_MSG_ACK = 22;

    ACCEPT_FRIEND_MSG = 23;
    ACCEPT_FRIEND_MSG_ACK = 24;

    FRIEND_ACCEPT_NOTIFY_MSG = 25;
    FRIEND_ACCEPT_NOTIFY_MSG_ACK = 26;

    QUERY_FRIEND_MSG = 27;
    QUERY_FRIEND_MSG_ACK = 28;

    DELETE_FRIEND_MSG = 29;
    DELETE_FRIEND_MSG_ACK = 30;

    GROUP_HISTORY_MSG = 31;
    GROUP_HISTORY_MSG_ACK = 32;

    FILE_START_MSG = 33;
    FILE_START_MSG_ACK = 34;

    FILE_CHUNK_MSG = 35;
    FILE_CHUNK_MSG_ACK = 36;

    FILE_END_MSG = 37;
    FILE_END_MSG_ACK = 38;

    DOWNLOAD_FILE_MSG = 39;
    DOWNLOAD_FILE_MSG_ACK = 40;

    DOWNLOAD_START_MSG = 41;
    DOWNLOAD_START_MSG_ACK = 42;

    DOWNLOAD_CHUNK_MSG = 43;
    DOWNLOAD_CHUNK_MSG_ACK = 44;

    DOWNLOAD_END_MSG = 45;
    DOWNLOAD_END_MSG_ACK = 46;

    CANCEL_ACCOUNT_MSG = 47;
    CANCEL_ACCOUNT_MSG_ACK = 48;

    APPLY_GROUP_MSG = 49;
    APPLY_GROUP_MSG_ACK = 50;

    QUERY_GROUP_REQ_MSG = 51;
    QUERY_GROUP_REQ_MSG_ACK = 52;

    ACCEPT_GROUP_MSG = 53;
    ACCEPT_GROUP_MSG_ACK = 54;

    GROUP_NOTIFY_MSG = 55;
    GROUP_NOTIFY_MSG_ACK = 56;

    GROUP_ACCEPT_NOTIFY_MSG = 57;
    GROUP_ACCEPT_NOTIFY_MSG_ACK = 58;

    QUERY_GROUP_MSG = 59;
    QUERY_GROUP_MSG_ACK = 60;

    LEAVE_GROUP_MSG = 61;
    LEAVE_GROUP_MSG_ACK = 62;

    TRANSFER_OWNER_MSG = 63;
    TRANSFER_OWNER_MSG_ACK = 64;

    DISSOLVE_GROUP_MSG = 65;
    DISSOLVE_GROUP_MSG_ACK = 66;

    QUERY_GROUP_USER_MSG = 67;
    QUERY_GROUP_USER_MSG_ACK = 68;

    SET_GROUP_ADMIN_MSG = 69;
    SET_GROUP_ADMIN_MSG_ACK = 70;

    REMOVE_GROUP_ADMIN_MSG = 71;
    REMOVE_GROUP_ADMIN_MSG_ACK = 72;

    REMOVE_GROUP_USER_MSG = 73;
    REMOVE_GROUP_USER_MSG_ACK = 74;

    REMOVE_GROUP_USER_NOTIFY_MSG = 75;
    REMOVE_GROUP_USER_NOTIFY_MSG_ACK = 76;

    REFUSE_GROUP_MSG = 77;
    REFUSE_GROUP_MSG_ACK = 78;

    REFUSE_GROUP_NOTIFY_MSG = 79;
    REFUSE_GROUP_NOTIFY_MSG_ACK = 80;

    GROUP_FILE_NOTIFY_MSG = 81;
    GROUP_FILE_NOTIFY_MSG_ACK = 82;

    BLACKLIST_ADD_MSG = 83;
    BLACKLIST_ADD_MSG_ACK = 84;

    BLACKLIST_REMOVE_MSG = 85;
    BLACKLIST_REMOVE_MSG_ACK = 86;

    SEND_CODE_MSG = 87;
    SEND_CODE_MSG_ACK = 88;

    CODE_LOGIN_MSG = 89;
    CODE_LOGIN_MSG_ACK = 90;

    RESET_PASSWORD_MSG = 91;
    RESET_PASSWORD_MSG_ACK = 92;

    VERIFY_CODE_MSG = 93;
    VERIFY_CODE_MSG_ACK = 94;

    PING_MSG = 95;
    PONG_MSG = 96;

    QUERY_FILE_MSG = 97;
    QUERY_FILE_MSG_ACK = 98;

    CHECK_FRIEND_MSG = 99;
    CHECK_FRIEND_MSG_ACK = 100;

    CHECK_GROUP_MSG = 101;
    CHECK_GROUP_MSG_ACK = 102;

    INVITE_NOTIFY_MSG = 103;
    INVITE_NOTIFY_MSG_ACK = 104;

    LEAVE_NOTIFY_MSG = 105;
    LEAVE_NOTIFY_MSG_ACK = 106;
}

message OfflineMsg {
    int32 fromid = 1;
    int32 toid = 2;
    string msg = 3;
    string time = 4;
}

message LoginReq {
    MsgTyp msgid = 1;
    int32 id = 2;
    string password = 3;
}

message LoginRes {
    int32 err = 1;
    string errmsg = 2;
    User user = 3;
    repeated OfflineMsg offlinemsgs = 4;
    repeated User friends = 5;
    repeated Group groups = 6;
    repeated OfflineGroupMsg offlinegroupmsg = 7;
    repeated OfflineFile offlinefiles = 8;
    repeated GroupFileNotify offlinegroupfiles = 9;
    repeated FriendRequest offlinefriendrequests = 10;
}

message RegisterReq {
    MsgTyp msgid = 1;
    string name = 2;
    string password = 3;
    string email = 4;
}

message RegisterRes {
    int32 err = 1;
    string errmsg = 2;
    int32 userid = 3;
}

message AddFriendReq {
    MsgTyp msgid = 1;
    int32 toid = 2;
}

message AddFriendRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message OneChatReq {
    MsgTyp msgid = 1;
    int32 toid = 2;
    string msg = 3;
    string time = 4;
}

message OneChatRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message CreateGroupReq {
    MsgTyp msgid = 1;
    string groupname = 2;
    string groupdesc = 3;
    int32 friendid = 4;
}

message CreateGroupRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
    int32 groupid = 4;
}

message AddGroupReq {
    MsgTyp msgid = 1;
    int32 groupid = 2;
}

message AddGroupRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message GroupChatReq {
    MsgTyp msgid = 1;
    int32 groupid = 2;
    string msg = 3;
    string time = 4;
}

message GroupChatRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message LogoutReq {
    MsgTyp msgid = 1;
}

message LogoutRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message User {
    int32 id = 1;
    string name = 2;
    string state = 3;
}

message GroupUser {
    int32 id = 1;
    string name = 2;
    string state = 3;
}

message Group {
    int32 id = 1;
    string name = 2;
    string desc = 3;
    repeated GroupUser users = 4;
    string role = 5;
}

message FriendFile {
    int32 fromid = 1;
    int32 toid = 2;
    string fileid = 3;
    string filename = 4;
    uint64 filesize = 5;
}

message HistoryMsg {
    int32 fromid = 1;
    int32 toid = 2;
    string msg = 3;
    string time = 4;
    string fromname = 5;
}

message HistoryMsgReq {
    int32 friendid = 1;
}

message HistoryMsgRes {
    int32 err = 1;
    string errmsg = 2;
    repeated HistoryMsg msgs = 3;
    repeated FriendFile files = 4;
}

message AcceptFriendReq {
    MsgTyp msgid = 1;
    int32 friendid = 2;
}

message AcceptFriendRes {
    int32 err = 1;
    string errmsg = 2;
}

message FriendRequest {
    int32 userid = 1;
    string username = 2;
}

message QueryFriendReqReq {
    MsgTyp msgid = 1;
}

message QueryFriendReqRes {
    int32 err = 1;
    string errmsg = 2;
    repeated FriendRequest requests = 3;
}

message FriendAcceptNotify {
    int32 userid = 1;
    string username = 2;
}

message QueryFriendReq {
    MsgTyp msgid = 1;
}

message QueryFriendRes {
    int32 err = 1;
    string errmsg = 2;
    repeated User friends = 3;
}

message DeleteFriendReq {
    int32 friendid = 1;
}

message DeleteFriendRes {
    int32 err = 1;
    string errmsg = 2;
}

message GroupFile {
    int32 userid = 1;
    int32 groupid = 2;
    string fileid = 3;
    string filename = 4;
    uint64 filesize = 5;
}

message GroupHistoryMsg {
    int32 groupid = 1;
    int32 userid = 2;
    string msg = 3;
    string time = 4;
}

message GroupHistoryMsgReq {
    int32 groupid = 1;
}

message GroupHistoryMsgRes {
    int32 err = 1;
    string errmsg = 2;
    repeated GroupHistoryMsg msgs = 3;
    repeated GroupFile files = 4;
}

message OfflineGroupMsg {
    int32 groupid = 1;
    int32 userid = 2;
    string msg = 3;
    string time = 4;
}

message FileStartReq {
    int32 toid = 1;
    string filename = 2;
    uint64 filesize = 3;
    string fileid = 4;
    int32 groupid = 5;
}

message FileStartRes {
    int32 err = 1;
    string errmsg = 2;
}

message FileChunkReq {
    string fileid = 1;
    bytes data = 2;
}

message FileChunkRes {
    int32 err = 1;
    string errmsg = 2;
}

message FileEndReq {
    string fileid = 1;
}

message FileEndRes {
    int32 err = 1;
    string errmsg = 2;
}

message OfflineFile {
    int32 fromid = 1;
    int32 toid = 2;
    string filename = 3;
    uint64 filesize = 4;
    string fileid = 5;
    string fromname = 6;
}

message DownloadFileReq {
    string fileid = 1;
}

message DownloadFileRes {
    int32 err = 1;
    string errmsg = 2;
}

message DownloadStart {
    string fileid = 1;
    string filename = 2;
    uint64 filesize = 3;
}

message DownloadChunk {
    string fileid = 1;
    bytes data = 2;
    uint64 offset = 3;
}

message DownloadEnd {
    string fileid = 1;
}

message CancelAccountReq {
    MsgTyp msgid = 1;
}

message CancelAccountRes {
    int32 err = 1;
    string errmsg = 2;
}

message ApplyGroupReq {
    int32 groupid = 1;
}

message ApplyGroupRes {
    int32 err = 1;
    string errmsg = 2;
}

message QueryGroupReqReq {
    MsgTyp msgid = 1;
}

message GroupRequest {
    int32 userid = 1;
    string username = 2;
    int32 groupid = 3;
    string groupname = 4;
}

message QueryGroupReqRes {
    int32 err = 1;
    string errmsg = 2;
    repeated GroupRequest requests = 3;
}

message AcceptGroupReq {
    int32 groupid = 1;
    int32 targetid = 2;
}

message AcceptGroupRes {
    int32 err = 1;
    string errmsg = 2;
}

message QueryGroupReq {
    MsgTyp msgid = 1;
}

message QueryGroupRes {
    int32 err = 1;
    string errmsg = 2;
    repeated Group groups = 3;
}

message GroupAcceptNotify {
    int32 groupid = 1;
    string groupname = 2;
}

message LeaveGroupReq {
    int32 groupid = 1;
}

message LeaveGroupRes {
    int32 err = 1;
    string errmsg = 2;
}

message TransferOwnerReq {
    int32 newownerid = 1;
    int32 groupid = 2;
}

message TransferOwnerRes {
    int32 err = 1;
    string errmsg = 2;
}

message DissolveGroupReq {
    int32 groupid = 1;
}

message DissolveGroupRes {
    int32 err = 1;
    string errmsg = 2;
}

message QueryGroupUserReq {
    int32 groupid = 1;
}

message QueryGroupUserRes {
    int32 err = 1;
    string errmsg = 2;
    repeated GroupUserInfo users = 3;
}

message GroupUserInfo {
    int32 userid = 1;
    string username = 2;
    string role = 3;
}

message SetGroupAdminReq {
    int32 groupid = 1;
    int32 targetid = 2;
}

message SetGroupAdminRes {
    int32 err = 1;
    string errmsg = 2;
}

message RemoveGroupAdminReq {
    int32 groupid = 1;
    int32 targetid = 2;
}

message RemoveGroupAdminRes {
    int32 err = 1;
    string errmsg = 2;
}

message RemoveGroupUserReq {
    int32 groupid = 1;
    int32 targetid = 2;
}

message RemoveGroupUserRes {
    int32 err = 1;
    string errmsg = 2;
}

message RemoveGroupUserNotify {
    int32 groupid = 1;
    string groupname = 2;
}

message RefuseGroupReq {
    int32 groupid = 1;
    int32 targetid = 2;
}

message RefuseGroupRes {
    int32 err = 1;
    string errmsg = 2;
}

message RefuseGroupNotify {
    int32 groupid = 1;
    string groupname = 2;
}

message GroupFileNotify {
    int32 fromid = 1;
    string fromname = 2;
    int32 groupid = 3;
    string groupname = 4;
    string fileid = 5;
    string filename = 6;
    uint64 filesize = 7;
}

message BlacklistAddReq {
    int32 blackid = 1;
}

message BlacklistAddRes {
    int32 err = 1;
    string errmsg = 2;
}

message BlacklistRemoveReq {
    int32 blackid = 1;
}

message BlacklistRemoveRes {
    int32 err = 1;
    string errmsg = 2;
}

message OneChatNotify {
    int32 fromid = 1;
    string fromname = 2;
    string msg = 3;
    string time = 4;
}

message GroupChatNotify {
    int32 groupid = 1;
    int32 userid = 2;
    string username = 3;
    string msg = 4;
    string time = 5;
}

message SendCodeReq {
    string email = 1;
    int32 scene = 2;
}

message SendCodeRes {
    int32 err = 1;
    string errmsg = 2;
}

message CodeLoginReq {
    string email = 1;
    string code = 2;
}

message CodeLoginRes {
    int32 err = 1;
    string errmsg = 2;
    int32 userid = 3;
    string name = 4;
}

message ResetPasswordReq {
    string email = 1;
    string newpassword = 2;
}

message ResetPasswordRes {
    int32 err = 1;
    string errmsg = 2;
}

message VerifyCodeReq {
    string email = 1;
    string code = 2;
    int32 scene = 3;
}

message VerifyCodeRes {
    int32 err = 1;
    string errmsg = 2;
}

message FileNotify {
    int32 fromid = 1;
    string fromname = 2;
    string fileid = 5;
    string filename = 6;
    uint64 filesize = 7;
    int32 groupid = 8;
}

message QueryFileReq {
    MsgTyp msgid = 1;
}

message QueryFileRes {
    int32 err = 1;
    string errmsg = 2;
    repeated FileNotify files = 3;
}

message CheckFriendReq {
    int32 friendid = 1;
}

message CheckFriendRes {
    int32 err = 1;
    string errmsg = 2;
}

message CheckGroupReq {
    int32 groupid = 1;
}

message CheckGroupRes {
    int32 err = 1;
    string errmsg = 2;
}

message InviteNotify {
    int32 groupid = 1;
    string groupname = 2;
    int32 ownerid = 3;
}

message LeaveNotify {
    int32 userid = 1;
    string username = 2;
    int32 groupid = 3;
}