syntax = "proto3";
package chat;

enum MsgTyp {
    UNKNOWN_MSG = 0;

    LOGIN_MSG = 1;
    LOGIN_MSG_ACK = 2;

    REG_MSG = 3;
    REG_MSG_ACK = 4;

    ADD_FRIEND_MSG = 5;
    ADD_FRIEND_MSG_ACK = 6;

    ONE_CHAT_MSG = 7;
    ONE_CHAT_MSG_ACK = 8;

    CREATE_GROUP_MSG = 9;
    CREATE_GROUP_MSG_ACK = 10;

    ADD_GROUP_MSG = 11;
    ADD_GROUP_MSG_ACK = 12;

    GROUP_CHAT_MSG = 13;
    GROUP_CHAT_MSG_ACK = 14;

    LOGOUT_MSG = 15;
    LOGOUT_MSG_ACK = 16;

    HISTORY_MSG = 17;
    HISTORY_MSG_ACK = 18;

    FRIEND_NOTIFY_MSG = 19;
    FRIEND_NOTIFY_MSG_ACK = 20;

    QUERY_FRIEND_REQ_MSG = 21;
    QUERY_FRIEND_REQ_MSG_ACK = 22;

    ACCEPT_FRIEND_MSG = 23;
    ACCEPT_FRIEND_MSG_ACK = 24;

    FRIEND_ACCEPT_NOTIFY_MSG = 25;
    FRIEND_ACCEPT_NOTIFY_MSG_ACK = 26;

    QUERY_FRIEND_MSG = 27;
    QUERY_FRIEND_MSG_ACK = 28;

    DELETE_FRIEND_MSG = 29;
    DELETE_FRIEND_MSG_ACK = 30;

    GROUP_HISTORY_MSG = 31;
    GROUP_HISTORY_MSG_ACK = 32;

    FILE_START_MSG = 33;
    FILE_START_MSG_ACK = 34;

    FILE_CHUNK_MSG = 35;
    FILE_CHUNK_MSG_ACK = 36;

    FILE_END_MSG = 37;
    FILE_END_MSG_ACK = 38;

    DOWNLOAD_FILE_MSG = 39;
    DOWNLOAD_FILE_MSG_ACK = 40;

    DOWNLOAD_START_MSG = 41;
    DOWNLOAD_START_MSG_ACK = 42;

    DOWNLOAD_CHUNK_MSG = 43;
    DOWNLOAD_CHUNK_MSG_ACK = 44;

    DOWNLOAD_END_MSG = 45;
    DOWNLOAD_END_MSG_ACK = 46;

    CANCEL_ACCOUNT_MSG = 47;
    CANCEL_ACCOUNT_MSG_ACK = 48;
}

message OfflineMsg {
    int32 fromid = 1;
    int32 toid = 2;
    string msg = 3;
    string time = 4;
}

message LoginReq {
    MsgTyp msgid = 1;
    int32 id = 2;
    string password = 3;
}

message LoginRes {
    int32 err = 1;
    string errmsg = 2;
    User user = 3;
    repeated OfflineMsg offlinemsgs = 4;
    repeated User friends = 5;
    repeated Group groups = 6;
    repeated OfflineGroupMsg offlinegroupmsg = 7;
    repeated OfflineFile offlinefiles = 8;
}

message RegisterReq {
    MsgTyp msgid = 1;
    string name = 2;
    string password = 3;
}

message RegisterRes {
    int32 err = 1;
    string errmsg = 2;
    int32 userid = 3;
}

message AddFriendReq {
    MsgTyp msgid = 1;
    int32 fromid = 2;
    int32 toid = 3;
}

message AddFriendRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message OneChatReq {
    MsgTyp msgid = 1;
    int32 fromid = 2;
    int32 toid = 3;
    string msg = 4;
    string time = 5;
    string fromname = 6;
}

message OneChatRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message CreateGroupReq {
    MsgTyp msgid = 1;
    int32 userid = 2;
    string groupname = 3;
    string groupdesc = 4;
}

message CreateGroupRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
    int32 groupid = 4;
}

message AddGroupReq {
    MsgTyp msgid = 1;
    int32 userid = 2;
    int32 groupid = 3;
    string role = 4;
}

message AddGroupRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message GroupChatReq {
    MsgTyp msgid = 1;
    int32 groupid = 2;
    int32 userid = 3;
    string msg = 4;
    string time = 5;
    string username = 6;
}

message GroupChatRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message LogoutReq {
    MsgTyp msgid = 1;
    int32 userid = 2;
}

message LogoutRes {
    MsgTyp msgid = 1;
    int32 err = 2;
    string errmsg = 3;
}

message User {
    int32 id = 1;
    string name = 2;
    string state = 3;
}

message GroupUser {
    int32 id = 1;
    string name = 2;
    string state = 3;
}

message Group {
    int32 id = 1;
    string name = 2;
    string desc = 3;
    repeated GroupUser users = 4;
}

message HistoryMsgReq {
    int32 fromid = 1;
    int32 toid = 2;
    string msg = 3;
    string time = 4;
}

message HistoryMsgRes {
    int32 err = 1;
    string errmsg = 2;
    repeated HistoryMsgReq msgs = 3;
}

message AcceptFriendReq {
    MsgTyp msgid = 1;
    int32 userid = 2;
    int32 friendid = 3;
}

message AcceptFriendRes {
    int32 err = 1;
    string errmsg = 2;
}

message FriendRequest {
    int32 userid = 1;
    string username = 2;
}

message QueryFriendReqReq {
    MsgTyp msgid = 1;
    int32 userid = 2;
}

message QueryFriendReqRes {
    int32 err = 1;
    string errmsg = 2;
    repeated FriendRequest requests = 3;
}

message FriendAcceptNotify {
    int32 userid = 1;
    string username = 2;
}

message QueryFriendReq {
    int32 userid = 1;
}

message QueryFriendRes {
    int32 err = 1;
    string errmsg = 2;
    repeated User friends = 3;
}

message DeleteFriendReq {
    int32 userid = 1;
    int32 friendid = 2;
}

message DeleteFriendRes {
    int32 err = 1;
    string errmsg = 2;
}

message GroupHistoryMsgReq {
    int32 groupid = 1;
    int32 userid = 2;
    string msg = 3;
    string time = 4;
}

message GroupHistoryMsgRes {
    int32 err = 1;
    string errmsg = 2;
    repeated GroupHistoryMsgReq msgs = 3;
}

message OfflineGroupMsg {
    int32 groupid = 1;
    int32 userid = 2;
    string msg = 3;
    string time = 4;
}

message FileStartReq {
    int32 fromid = 1;
    int32 toid = 2;
    string filename = 3;
    uint64 filesize = 4;
    string fileid = 5;
}

message FileStartRes {
    int32 err = 1;
    string errmsg = 2;
}

message FileChunkReq {
    string fileid = 1;
    bytes data = 2;
    uint64 offset = 3;
}

message FileChunkRes {
    int32 err = 1;
    string errmsg = 2;
}

message FileEndReq {
    string fileid = 1;
}

message FileEndRes {
    int32 err = 1;
    string errmsg = 2;
}

message OfflineFile {
    int32 fromid = 1;
    int32 toid = 2;
    string filename = 3;
    uint64 filesize = 4;
    string fileid = 5;
    string fromname = 6;
}

message DownloadFileReq {
    string fileid = 1;
    int32 userid = 2;
}

message DownloadFileRes {
    int32 err = 1;
    string errmsg = 2;
}

message DownloadStart {
    string fileid = 1;
    string filename = 2;
    uint64 filesize = 3;
}

message DownloadChunk {
    string fileid = 1;
    bytes data = 2;
    uint64 offset = 3;
}

message DownloadEnd {
    string fileid = 1;
}

message CancelAccountReq {
    int32 userid = 1;
}

message CancelAccountRes {
    int32 err = 1;
    string errmsg = 2;
}